---
  # junction types to include from the junction_detail field
  valid_junction_types:
    # - no_junction_in_20m
    - roundabout
    - mini_roundabout
    - t_or_staggered_junction
    - slip_road
    - crossroads
    - multi_junction
    # - private_drive
    - other_junction
    - unknown

  valid_casualty_types:
    - pedal_cycle
    - pedestrian
  
  # tolerance level to determine which junctions to combine (in metres)
  tolerance: 15

  number_of_dangerous_collisions: 100
  distance_to_junction_threshold: .001

  # collision severity weights
  weight_fatal: 5
  weight_serious: 1
  weight_slight: .1

  # links to TfL csv data - shame they couldn't have chosen a consistent pattern!!
  data_links:
    - "https://content.tfl.gov.uk/jan-dec-2024-gla-data-extract-casualty.csv"
    - "https://content.tfl.gov.uk/jan-dec-2024-gla-data-extract-attendant.csv"
    - "https://content.tfl.gov.uk/jan-dec-2023-gla-data-extract-casualty.csv"
    - "https://content.tfl.gov.uk/jan-dec-2023-gla-data-extract-attendant.csv"
    - "https://content.tfl.gov.uk/jan-dec-2022-gla-data-extract-casualties.csv"
    - "https://content.tfl.gov.uk/jan-dec-2022-gla-data-extract-attendant.csv"
    - "https://content.tfl.gov.uk/jan-dec-2021-gla-data-extract-casualty.csv"
    - "https://content.tfl.gov.uk/jan-dec-2021-gla-data-extract-attendant.csv"
    - "https://content.tfl.gov.uk/2020-gla-data-extract-casualty.csv"
    - "https://content.tfl.gov.uk/2020-gla-data-extract-attendant.csv"
    # - "https://content.tfl.gov.uk/2019-gla-data-extract-attendant.csv"
    # - "https://content.tfl.gov.uk/2019-gla-data-extract-casualty.csv"

  # columns required from raw data
  collision_columns:
    - raw_collision_id
    - borough
    - easting
    - northing
    - location
    - collision_severity
    - junction_detail
    - date
    - time

  casualty_columns:
    - raw_collision_id
    - casualty_id
    - casualty_class
    - casualty_gender
    - number_of_casualties
    - casualty_severity
    - mode_of_travel
      
  # only read in necessary cols to keep data size down
  collision_app_columns:
    - borough
    - collision_index
    - year
    - longitude
    - latitude
    - is_cyclist_collision
    - is_pedestrian_collision
    - junction_id
    - junction_index
    - fatal_cyclist_casualties
    - serious_cyclist_casualties
    - slight_cyclist_casualties
    - fatal_pedestrian_casualties
    - serious_pedestrian_casualties
    - slight_pedestrian_casualties
    - recency_weight
    - date
    - max_cyclist_severity
    - max_pedestrian_severity

  junction_app_columns:
    - latitude_junction
    - longitude_junction
    - junction_id
    - junction_index
    - junction_cluster_id
    - junction_cluster_name
    - latitude_cluster
    - longitude_cluster